---
- name: Restart apache2
  become: true
  ansible.builtin.systemd:
    name: apache2.service
    state: restarted

- name: Restart php-fpm
  become: true
  ansible.builtin.systemd:
    name: "php{{ php_version }}-fpm.service"
    state: restarted
