---
- name: Download Nextcloud Release
  ansible.builtin.get_url:
    url: "{{ nextcloud_release }}"
    dest: "{{ nextcloud_release_download_dest }}"
    checksum: "{{ nextcloud_checksum }}"
    mode: "0400"

- name: Install Bzip2 to extract the Nextcloud release
  ansible.builtin.package:
    update_cache: true
    name: bzip2
    state: present

- name: Extract Nextcloud Release
  become: true
  ansible.builtin.unarchive:
    src: "{{ nextcloud_release_download_dest }}"
    dest: /var/www/
    creates: /var/www/nextcloud
    remote_src: true
    mode: "0755"
    group: "www-data"
    owner: "www-data"

- name: Nextcloud storage config
  ansible.builtin.template:
    src: storage.config.php.j2
    dest: /var/www/nextcloud/config/storage.config.php
    mode: "0755"
    group: "www-data"
    owner: "www-data"
  when: "nextcloud_s3_region is defined"

- name: Nextcloud autoconfig
  ansible.builtin.template:
    src: autoconfig.php.j2
    dest: /var/www/nextcloud/config/autoconfig.php
    mode: "0755"
    group: "www-data"
    owner: "www-data"
