galaxy_info:
  author: Mattherix
  description: Install mariadb in the context of a nextcloud install (for my home lab)
  license: EFL-2.0
  min_ansible_version: 2.1

  platforms:
    - name: Debian
      versions:
        - "bullseye"

  galaxy_tags:
    - "nextcloud"
    - "mariadb"

dependencies: []
